wandb_version: 1

learning_rate:
  desc: null
  value: 0.001
architecture:
  desc: null
  value: CNN
dataset:
  desc: null
  value: H3.6
epochs:
  desc: null
  value: 30
_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.15.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1683110703.567739
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.10.11
      5: 0.15.1
      8:
      - 5
