wandb_version: 1

learning_rate:
  desc: null
  value: 0.005
architecture:
  desc: null
  value: CNN
dataset:
  desc: null
  value: H3.6
epochs:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.9.6
    cli_version: 0.15.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1684175718.439684
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.9.6
      5: 0.15.2
      8:
      - 4
      - 5
